spring.application.name=clinicmanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_system
spring.datasource.username=postgres
spring.datasource.password=Admin
spring.jpa.hibernate.ddl-auto=update
server.port=1015
